blank_issues_enabled: false
contact_links:
  - name: Discuss in Discussions
    url: https://github.com/HassanCodeX/ai-dev-newsletter/discussions
    about: Use this for general questions or support requests.
